# commit to be tagged for new release
commit = "HEAD"

project_name = "Sidero"
github_repo = "siderolabs/sidero"
match_deps = "^github.com/(siderolabs/[a-zA-Z0-9-]+)$"

# previous release
previous = "v0.6.14"

pre_release = false

preface = """\
"""

[notes]

[notes.talos]
    title = "Talos"
   description = """\
Sidero Metal is now compatible with Talos v1.14.x.
"""
